---
name: CI
"on":
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 5"

defaults:
  run:
    working-directory: "tolecnal.tmux_tpm"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "tolecnal.tmux_tpm"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install APT packages
        run: sudo apt install python3-jmespath -y

      - name: Install test dependencies.
        run: pip3 install yamllint ansible ansible-lint jmespath

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: ${{ !contains(github.event_name, 'pull_request') }}
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2004
          - debian11
          - debian12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "tolecnal.tmux_tpm"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install APT packages
        run: sudo apt install python3-jmespath -y

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker jmespath

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
