---
name: Release
"on":
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: "tolecnal.tmux_npm"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: "tolecnal.tmux_npm"

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
